COLLECT_WHOIS_OF_GOOD_DOMAINS = 1
COLLECT_WHOIS_OF_BAD_DOMAINS = 2
CHOICE_OF_COLLECT_GOOD = 1          # 为正常域名收集信息
CHOICE_OF_COLLECT_BAD = 0           # 为恶意域名收集信息
CHOICE_OF_ANALYIZE_GOOD = 1         # 分析正常域名特征
CHOICE_OF_ANALYIZE_BAD = 0          # 分析恶意域名特征
